name: IlluminatiFly
version: ${project.version}
main: me.illuminatiproductions.illuminatifly.IlluminatiFly
api-version: 1.13
authors: [Illuminatiiiiii]
description: Allows players to fly, with style
website: https://youtube.com/c/IlluminatiProductions
commands:
  fly:
    description: Fly like a bird
    usage: /<command>
